### ISSUE TITLE
converter is Thread Block

### ISSUE THREAD

**Issue by aloisogomes** [hckrnews/converter#11]
This library is blocking server, because it uses a lot of blocking methods like execSync, existsSync
so when you try use this as service in express for instance, it block all server until process end.

There are any reason to keep it synchonous?:

**Comment by w3nl** [comment]
Hi, sorry for the late reaction, i have missed your message.
It is now indeed blocking, because it was usefull for me on a project.
I think i will add soon an option to choose if you if you need it blocking or async.

**Comment by IlyaSovenko** [comment]
Hi! And when can it be implemented? I wondering, because I'm just thinking about moving this in another script, create separate thread for this and so on, and if it can be easily fixed for me by just by passing this option - this would be awesome

**Comment by w3nl** [comment]
I add it now.
You can always add a PR with new features if you need something.

**Comment by w3nl** [comment]
Added in version `0.4.5`
https://github.com/hckrnews/converter/releases/tag/0.4.5
